development:
  cloud_name: "bhanu"
  api_key: "973218773625518"
  api_secret: "-o8sbuIaBkL-1r4R-2ehwCrApgQ"

production:
  cloud_name: "bhanu"
  api_key: "973218773625518"
  api_secret: "-o8sbuIaBkL-1r4R-2ehwCrApgQ"